import random
import os
from typing import Dict, List, Tuple

def generate_map_file(filename: str, width: int, height: int, noise_level: float = 0.1) -> None:
    """
    Génère un fichier .map avec une élévation aléatoire.
    """
    print(f"Génération de la carte {width}x{height} dans '{filename}'...")
    
    with open(filename, 'w') as f:
        f.write("# Map Generated by MedievAIl CLI\n")
        f.write(f"SIZE: {width} {height}\n")
        f.write("GRID:\n")
        
        for y in range(height):
            row = []
            for x in range(width):
                # Simple random elevation logic or Perlin noise could be here
                # Pour l'instant, simple random weighted by noise_level to create "hills"
                # Mais simplifions : 0 par défaut, avec des zones aléatoires d'élévation
                
                # Base elevation
                elev = 0
                if random.random() < noise_level:
                    elev = random.randint(1, 3)
                
                row.append(str(elev))
            f.write(" ".join(row) + "\n")
            
    print(f"✅ Carte créée : {filename}")

def generate_army_file(filename: str, general_name: str, units_config: Dict[str, int], map_size: Tuple[int, int], army_id: int) -> None:
    """
    Génère un fichier d'armée .txt avec des positions aléatoires valides.
    army_id determines spawn side (0 = left/top, 1 = right/bottom generally)
    """
    print(f"Génération de l'armée pour {general_name} dans '{filename}'...")
    
    width, height = map_size
    
    # Spawn zones
    margin = 5
    if army_id == 0:
        x_min, x_max = margin, width // 3
        y_min, y_max = margin, height - margin
    else:
        x_min, x_max = (width // 3) * 2, width - margin
        y_min, y_max = margin, height - margin
        
    with open(filename, 'w') as f:
        f.write(f"# Army Generated by MedievAIl CLI\n")
        f.write(f"GENERAL: {general_name}\n")
        f.write("# Format: UnitType, X, Y\n")
        
        for unit_type, count in units_config.items():
            for _ in range(count):
                x = random.uniform(x_min, x_max)
                y = random.uniform(y_min, y_max)
                f.write(f"{unit_type}, {x:.2f}, {y:.2f}\n")
                
    print(f"✅ Armée créée : {filename}")
